#!/bin/bash

set -o errexit -o nounset -o pipefail

process_entry() {
	local X="$1" Y="$2" file="$3"

	# diff
	#
	if [[ "$X" =~ ^[MTAD]$ ]]; then
		echo git diff --cached -- "$file"
	fi
	if [[ "$Y" =~ ^[MTAD]$ ]]; then
		echo git diff -- "$file"
	fi

	# untracked file
	#
	if [[ "$X$Y" == '??' ]]; then
		echo git add "$file"
		echo rm "$file"
		return
	fi

	# renamed file
	#
	if [[ "$X" == 'R' ]]; then
		read -r src _ dst <<<"$file"
		echo git mv "$dst" "$src"
		return
	fi

	# untracked file but in the index
	#
	if [[ "$X$Y" == ' A' ]]; then
		echo git add "$file"
		echo git reset HEAD "$file"
		return
	fi

	# move back and forth to the index
	#
	if [[ "$X" =~ ^[MTAD]$ ]]; then
		echo git reset HEAD "$file"
	fi
	if [[ "$Y" =~ ^[MTAD]$ ]]; then
		echo git add "$file"
		echo git checkout "$file"
	fi
}

if wt="$(git rev-parse --is-inside-work-tree 2>/dev/null)"; [[ "$wt" != 'true' ]]; then
	exit 1
fi

IFS= read -r str

if ! git status --porcelain | grep -q --line-regexp --fixed-strings -- "$str"; then
	exit 1
fi

process_entry "${str:0:1}" "${str:1:1}" "${str:3}"
