#!/bin/bash

read -r str

if s="${str//[[:blank:]]/}"; ! [[
	"$s" =~ ^[a-zA-Z0-9]{16}$ ||
	"$s" =~ ^[a-zA-Z0-9]{26}$ ||
	"$s" =~ ^[a-zA-Z0-9]{32}$
]]; then
	exit 1
fi

if ! oathtool -b --totp "$str" >/dev/null 2>&1; then
	exit 1
fi

cat <<-EOF
	oathtool -b --totp ${str@Q}
EOF
