#!/bin/bash

read -r str

if [[ ! "$str" =~ ^/tmp/scrot/. ]]; then
	exit 1
fi

image="$XDG_RUNTIME_DIR${str#/tmp}"

if [[ -e "$image" ]]; then
	exit 1
fi

if dir="${image%/*}"; [[ ! -e "$dir" ]]; then
	echo mkdir -p -- "${dir@Q}"
fi

cat <<-EOF
	sleep 5s
	maim --hidecursor --select -- ${image@Q}

	xclip -selection clipboard -target image/png -in <${image@Q}
	rm -- ${image@Q}
EOF
