#!/bin/bash

read -r str

if [[ ! "$str" =~ ^/tmp/scrot/. ]]; then
	exit 1
fi

if [[ ! -e "${str%/*}" ]]; then
	echo mkdir -p "${str%/*}"
fi

if [[ ! -e "$str" ]]; then
	cat <<-EOF
		sleep 5s
		maim --hidecursor --select -- ${str@Q}
		xclip -selection clipboard -target image/png -in <${str@Q}
		rm -- ${str@Q}
	EOF
fi
