#!/bin/bash

read -r str

if [[ ! "$str" =~ ^/tmp/scrot/. ]]; then
	exit 1
fi

str="$XDG_RUNTIME_DIR${str#/tmp}"

if dir="${str%/*}"; [[ ! -e "$dir" ]]; then
	echo mkdir -p "$dir"
fi

if [[ ! -e "$str" ]]; then
	cat <<-EOF
		sleep 5s
		maim --hidecursor --select -- ${str@Q}

		xclip -selection clipboard -target image/png -in <${str@Q}
		rm -- ${str@Q}
	EOF
fi
