#!/bin/bash

read -r -a units

if (( ${#units[@]} == 0 )); then
	exit 1
fi

system_service_manager=0 user_service_manager=0

if systemd-analyze verify -- "${units[@]}" >/dev/null 2>&1; then
	system_service_manager=1
fi

if systemd-analyze --user verify -- "${units[@]}" >/dev/null 2>&1; then
	user_service_manager=1
fi

if (( !system_service_manager && !user_service_manager )); then
	exit 1
fi

if (( system_service_manager )); then
	cat <<-EOF
		systemctl restart -- ${units[@]@Q}
		$(printf "systemctl status -- %s\n" "${units[@]@Q}")
		journalctl --follow $(printf -- '--unit=%s ' "${units[@]@Q}")
	EOF
fi

if (( user_service_manager )); then
	cat <<-EOF
		systemctl --user restart -- ${units[@]@Q}
		$(printf "systemctl --user status -- %s\n" "${units[@]@Q}")
		journalctl --user --follow $(printf -- '--unit=%s ' "${units[@]@Q}")
	EOF
fi
