#!/bin/bash

list_system_units() {
	systemctl -o json --all list-units -- "$1" \
	| jq --raw-output '.[].unit'
}

list_system_unit_files() {
	systemctl -o json list-unit-files -- "$1" \
	| jq --raw-output '.[].unit_file'
}

list_user_units() {
	systemctl -o json --all --user list-units -- "$1" \
	| jq --raw-output '.[].unit'
}

list_user_unit_files() {
	systemctl -o json --user list-unit-files -- "$1" \
	| jq --raw-output '.[].unit_file'
}

read -r unit

list_funcs=(
	list_system_units
	list_system_unit_files
	list_user_units
	list_user_unit_files
)

for f in "${list_funcs[@]}"; do
	if [[ "$("$f" "$unit" | head -1)" != "$unit" ]]; then
		"$f" "$unit"
	fi
done | sort --unique
