#!/bin/bash

list_system_units() {
	systemctl -o json --all list-units -- "$1" \
	| jq --raw-output '.[].unit'
}

list_system_unit_files() {
	systemctl -o json list-unit-files -- "$1" \
	| jq --raw-output '.[].unit_file'
}

list_user_units() {
	systemctl -o json --all --user list-units -- "$1" \
	| jq --raw-output '.[].unit'
}

list_user_unit_files() {
	systemctl -o json --user list-unit-files -- "$1" \
	| jq --raw-output '.[].unit_file'
}

list_machines() {
	systemctl -o json list-machines -- "$1" \
	| jq --raw-output '.[].name'
}

list_funcs=(
	list_system_units
	list_user_units
	list_system_unit_files
	list_user_unit_files
)

read -r str

for f in "${list_funcs[@]}"; do
	if [[ "$("$f" "$str" | head -1)" != "$str" ]]; then
		"$f" "$str" \
		| sed 's/^.*\(\.[a-z^.]*\)$/\1 &/' \
		| sort --unique \
		| sed 's/^[^ ]* //'
	fi
done

if [[ "$(list_machines "$str" | head -1)" != "$str" ]]; then
	list_machines "$str"
fi
