#!/bin/bash

# assume $1 and $2 are already escaped
#
print_suggestions() {
	local systemctl="$1" journalctl="$2"
	shift 2
	local units=("$@")

	if (( ${#units[@]} > 1 )); then
		cat <<-EOF
			$systemctl restart -- ${units[*]@Q}
			$journalctl --follow $(printf -- '--unit=%s ' "${units[@]@Q}")
		EOF
	fi

	local u
	for u in "${units[@]}"; do
		cat <<-EOF
			$systemctl status -- ${u@Q}
			$systemctl restart -- ${u@Q}
			$systemctl stop -- ${u@Q}
			$systemctl --full edit -- ${u@Q}
			$journalctl --follow --unit=${u@Q}
		EOF
	done
}

read -r -a units

if (( ${#units[@]} == 0 )); then
	exit 1
fi

if systemd-analyze verify -- "${units[@]}" >/dev/null 2>&1; then
	print_suggestions 'systemctl' 'journalctl' "${units[@]}"
fi

if systemd-analyze --user verify -- "${units[@]}" >/dev/null 2>&1; then
	print_suggestions 'systemctl --user' 'journalctl --user' "${units[@]}"
fi
