#!/bin/bash

extract_host() {
	trurl --verify --get '{host}' --url "$url" 2>/dev/null
}

read -r url

if ! h="$(extract_host "$url")"; then
	exit 1
fi

case "$h" in
*.youtube.com|youtube.com|youtu.be)
	cat <<-EOF
		mpv --no-video ${url@Q}
	EOF
	;;
esac
